### ISSUE TITLE
Filtros de búsqueda laterales

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/biodiversity_catalogue_v2_frontend#184]
@jag2kn van mockups de filtros de búsqueda para barra lateral: 

PNG: 
![cbc-filtros-leterales](https://user-images.githubusercontent.com/14220404/33893486-7e639460-df29-11e7-9ad8-2fdef7ad9ecc.png)

PDF:
[CBC-filtros-leterales.pdf](https://github.com/SIB-Colombia/biodiversity_catalogue_v2_frontend/files/1552205/CBC-filtros-leterales.pdf)

**Comment by camiplata** [comment]
Los filtros están completos excepto el de Ecosistemas
@javiesgm el filtro de ecosistemas se mantiene o se retira?, la fuente naranja se mantiene?

**Comment by javiesgm** [comment]
Como están están bien
