### ISSUE TITLE
Tamaño - Slider HOME 

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/biodiversity_catalogue_v2_frontend#186]
Propongo que el alto sea de 550px para el slider del home. 

Creo que esta es la clase a la que se le aplicaría este estilo. 

.uk-slideshow-items {
    height: 550px;
}

[Uploading... Captura de pantalla 2018-02-01 a la(s) 2.09.55 p. m..png ]

**Comment by jag2kn** [comment]
Se ajustó proporcional
