### ISSUE TITLE
Imagen destacada para ficha de especie

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/biodiversity_catalogue_v2_frontend#187]
Configurar el margen a  --> margin-top: 60vh;

![Captura de pantalla 2018-02-01 a la(s) 2.11.31 p. m..png](https://images.zenhubusercontent.com/56d4a9026caf56c9d38d0cdd/219a2567-0011-4271-8a12-12c853614cf9)

**Comment by dapino** [comment]
@javiesgm  a que margen se refiere este issue?

**Comment by javiesgm** [comment]
La distancia predeterminada para que se vea la imagen destacada.
