### ISSUE TITLE
HOME | cifras destacadas

### ISSUE THREAD

**Issue by dapino** [SIB-Colombia/biodiversity_catalogue_v2_frontend#207]
En las cifras destacadas, ocultar la cifras de usuarios.

![Screen Shot 2018-06-08 at 10.51.36 AM.png](https://images.zenhubusercontent.com/5b0ed04054b51e4165e1d59d/3946a222-ac42-47e5-9c81-3d90f039beaf)

Relacionado: #208

**Comment by camiplata** [comment]
@dapino @javiesgm que va a pasar con las de flora y fauna?

**Comment by javiesgm** [comment]
@camiplata lo que se acordó, aunque siempre sujeto a revisión, es que las cifras estuvieran relacionadas con especies, álbumes y usuarios, y no con grupos biológicos.

Por ahora, solo especies, aunque sea impreciso.

**Comment by camiplata** [comment]
ok, entonces el issue fue resuelto
