### ISSUE TITLE
BÚSQUEDA | Número de resultados 

### ISSUE THREAD

**Issue by dapino** [SIB-Colombia/biodiversity_catalogue_v2_frontend#210]
Mostrar número de resultados de la consulta.

![Screen Shot 2018-06-08 at 11.10.48 AM.png](https://images.zenhubusercontent.com/5b0ed04054b51e4165e1d59d/4d13a58b-ee20-4d11-9ac7-9a77c54c7ecb)

Relacionado: #211

**Comment by jag2kn** [comment]
Se ajustó arriba y también se colocó abajo en el botón para saber el estado actual
