### ISSUE TITLE
BÚSQUEDA | Paginación

### ISSUE THREAD

**Issue by dapino** [SIB-Colombia/biodiversity_catalogue_v2_frontend#211]
Mostrar paginación según mockup, en su defecto un _lazy load_ que cargue cuando se llegue al fondo de la página. 
![screen shot 2018-06-08 at 11 21 35 am](https://user-images.githubusercontent.com/11689269/41169288-2274c158-6b0e-11e8-9c43-e93e74e78293.png)

Relacionado: #210

**Comment by jag2kn** [comment]
Se implementó carga con botón "ver más"

**Comment by jag2kn** [comment]
Se colocó información de cuantos elementos existen en el momento

**Comment by javiesgm** [comment]
Excelente!
