### ISSUE TITLE
FICHA | Taxonomía

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#212]
El campo 'Especie' en la taxonomía del resumen de la ficha aparece vacío, o la información no corresponde a la especie. Eliminar por completo este elemento.

![image](https://user-images.githubusercontent.com/5700527/42337879-ab5bab90-804d-11e8-973f-eff6b11bc805.png)

**Comment by jag2kn** [comment]
Se eliminó y se colocó en cursiva el género
