### ISSUE TITLE
DETALLE ESPECIE | Organización elementos Jerarquía

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#214]
En el detalle de la ficha, los elementos de la Jerarquía aparecen en distinto orden para las fichas creadas manualmente  (imagen 1) y las que se crearon automáticamente (imagen 2). El orden deseado para la jerarquía se mestra en la (imagen 3). 

Jerarquía en fichas creadas automáticamente:
![image](https://user-images.githubusercontent.com/5700527/42341988-73e1782c-805a-11e8-85fb-495f8bdfaa1e.png)

Jerarquía en fichas creadas manualmente:
![image](https://user-images.githubusercontent.com/5700527/42342537-ffd76408-805b-11e8-967a-9bb2e4c75e1b.png)

Ejemplo del orden en que debe aparecer la jerarquía:
**Advertencia**, se debe mostrar **solo** los elementos de la Jerarquía que contienen información.
![image](https://user-images.githubusercontent.com/5700527/42343734-9e50835a-805f-11e8-87c9-d16c81118e68.png)

**Comment by camiplata** [comment]
URL's asociadas al issue:

http://catalogo.biodiversidad.co/file/5b2cd3748c02d26812a591ba/summary

http://catalogo.biodiversidad.co/file/56cb8057207ecea54a561df4/summary

**Comment by jag2kn** [comment]
Ajustado

**Comment by camiplata** [comment]
El ajuste incluyó eliminar el campo taxón parental; y reorganizar los contenidos.

@camiplata Crear un nuevo Issue para determinar  donde va categoría del taxón
