### ISSUE TITLE
DETALLE ESPECIE | Alineación referencias

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#217]
El contenido del texto se debe ajustar a la 'caja' de la sección.

Ver Bug en la imagen:
![image](https://user-images.githubusercontent.com/5700527/42348911-a7420e00-8070-11e8-8513-9163996e4025.png)

**Comment by jag2kn** [comment]
@camiplata me puedes regalar la url porfa

**Comment by camiplata** [comment]
Url de la ficha donde se detecto el Issue
http://catalogo.biodiversidad.co/file/56cb8057207ecea54a561df4/details

**Comment by jag2kn** [comment]
Hecho
