### ISSUE TITLE
DETALLE FICHA | Nombre del Taxón

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#218]
El nombre científico en la sección 'Nombre del taxón' (#213 ) debe aparecer en  letra cursiva

![image](https://user-images.githubusercontent.com/5700527/42349125-3f895d62-8071-11e8-8066-0a1ab3f40282.png)

**Comment by jag2kn** [comment]
Solucionado
