### ISSUE TITLE
REDIRECCIONAMIENTO CÓDIGOS QR - Fichas Bitácora flora páramo

### ISSUE THREAD

**Issue by ghost** [SIB-Colombia/biodiversity_catalogue_v2_frontend#219]
Los enlaces desde los códigos QR relacionados con la "Bitácora de flora. Guía visual de plantas de páramos de Colombia" http://repository.humboldt.org.co/handle/20.500.11761/9283 se encuentran rotos. Debemos:

1. Definir cual será la URL definitiva para las fichas en el Catálogo (ideal mantener el ID de ficha).
2. Solicitar el redireccionamiento de todas esas URL antiguas a las nuevas. Se adjunta lista de las fichas a redireccionar: [Fichas Páramo URL.xlsx](https://github.com/SIB-Colombia/catalogo-de-la-biodiversidad-frontend/files/2193245/Fichas.Paramo.URL.xlsx)

**Comment by jag2kn** [comment]
Lista de ids anteriores:

```
db.RecordVersion.distinct("legacy_id")
```


Forma de consultar los ids:

```
db.RecordVersion.find({"legacy_id":"4774"})
db.TaxonRecordNameVersion.find({"_id":ObjectId("5762c31ae1b68a831a80b7f4")})
```

**Comment by jag2kn** [comment]
En el dominio principal se hace la redirección al catalogo si la url es  ```ficha/:id``` y en el catalogo hace la búsqueda con ese id en los legacy ubicando y mostrando la ficha correcta:

 * http://www.biodiversidad.co/fichas/1975
 * http://catalogo.biodiversidad.co/fichas/1975
 * http://catalogo.biodiversidad.co/file/56d9c5ce3c16479905cba9bc/summary

**Comment by javiesgm** [comment]
💪
