### ISSUE TITLE
DETALLE DE ESPECIE | Referencias - cómo deben mostrarse

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/biodiversity_catalogue_v2_frontend#222]
@jag2kn incluyo mockups de cómo deben mostrarse las referencias

PDF - detalle de ficha completo: 
[Uploading... detalle-ficha2018.pdf ]

PNG (detalle): 
![Captura de pantalla 2018-08-08 a la(s) 3.56.24 p. m..png](https://images.zenhubusercontent.com/56d4a9026caf56c9d38d0cdd/1e633044-acc1-44ed-8e26-317a0e6ddd00)

**Comment by jag2kn** [comment]
@camiplata 

http://api.catalogo.biodiversidad.co/api/v1.5/complete-record/59f11bdf5f3693434430faf8

**Comment by jag2kn** [comment]
Hecho

**Comment by jag2kn** [comment]
![captura de pantalla de 2018-08-14 17-20-13](https://user-images.githubusercontent.com/321637/44121680-7cce7600-9fe6-11e8-9d8f-b49f0532b82e.png)
