### ISSUE TITLE
BÚSQUEDA | resultados de búsqueda - ¿cuántos resultados arrojó mi búsqueda?

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/biodiversity_catalogue_v2_frontend#224]
Al hacer una búsqueda, por ejemplo: 
http://catalogo.biodiversidad.co/search/basic?q=chulo
PNG:
![Captura de pantalla 2018-08-08 a la(s) 4.03.10 p. m..png](https://images.zenhubusercontent.com/56d4a9026caf56c9d38d0cdd/0e49cab2-5f50-4846-bf61-e28ee67c05d6)

No hay una alerta o ayuda visual que me indique cuántos resultados arroja mi búsqueda. Esto confunde. 

Según mockups: 

![Captura de pantalla 2018-08-08 a la(s) 4.10.14 p. m..png](https://images.zenhubusercontent.com/56d4a9026caf56c9d38d0cdd/0902a937-ba03-487f-ab86-b11491fe574a)

**Comment by jag2kn** [comment]
Hecho
