### ISSUE TITLE
DETALLE FICHA | Sección 'Ancilliary data' duplicada

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#229]
Hay varias fichas donde aparecen dos cajas de 'Acilliary data'.
No es claro de donde proviene la segunda caja (debajo de 'Categoria'), la primera proviene de el campo 'Publicado en:'

![image](https://user-images.githubusercontent.com/5700527/43909933-19f07516-9bc1-11e8-80a4-f1a85f4d90e3.png)

Fichas ejemplo donde se deteectó el issue:
http://catalogo.biodiversidad.co/file/59f11bdf5f3693434430faf8/details
http://catalogo.biodiversidad.co/file/59f110aa5f3693434430f96d/details

**Comment by jag2kn** [comment]
Hecho

**Comment by javiesgm** [comment]
Proponemos que la referencia o fuente del nombre del taxón se incluya como información adicional en el nombre principal de la ficha.

**Comment by camiplata** [comment]
Ya aparece el tooltip pero no muestra la fuente:

![image](https://user-images.githubusercontent.com/5700527/48581434-caad8f80-e8ef-11e8-9833-70a78f55d9c0.png)

**Comment by jag2kn** [comment]
![contenidoextrataxonname](https://user-images.githubusercontent.com/321637/51214367-b3891f00-18eb-11e9-99ac-f9da015ddc5b.png)
