### ISSUE TITLE
DETALLE FICHA | Campo vacío de referencias

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#230]
Hay fichas donde el campo de referencias por sección aparece pero está vacío, esto sucede ya que desde mamut la sección tiene asignada una licencia pero no una referencia.

Debemos determianr si la licencia debe aparecer también, con que criterio la está selecionando el usuario (noto que simplemente la deja por defecto).

Ejemplo ficha en el catálogo:
![image](https://user-images.githubusercontent.com/5700527/43910510-a38bb2e4-9bc2-11e8-8b83-292c97d6d329.png)

Ejemplo ficha en Mamut:
![image](https://user-images.githubusercontent.com/5700527/43910547-bda29c56-9bc2-11e8-8cba-2d695363d4db.png)

Url ficha ejemplo:
http://catalogo.biodiversidad.co/file/56e462f383c45700544e3e36/details
http://prueba.mamut.biodiversidad.co/edit?id=56e462f383c45700544e3e36#/form/history

**Comment by camiplata** [comment]
También hay casos donde el campo de referencias aparece pero no hay ninguna referencia documentada en mamut.

Ejemplo
En catálogo
![image](https://user-images.githubusercontent.com/5700527/43915104-4e224a36-9bcf-11e8-8a40-cf946df410bf.png)
http://catalogo.biodiversidad.co/file/56718bdcf289f5a40c0cd305/details

En mamut:
![image](https://user-images.githubusercontent.com/5700527/43915132-6538c466-9bcf-11e8-91f9-d1f7502cd673.png)
http://prueba.mamut.biodiversidad.co/edit?id=56718bdcf289f5a40c0cd305#/form/demogra

**Comment by jag2kn** [comment]
Hecho

**Comment by javiesgm** [comment]
mm, pero el marco normativo sigue vacío. Así debe ir¿?

![captura de pantalla 2018-08-16 a la s 1 51 31 p m](https://user-images.githubusercontent.com/14220404/44228719-96dd9500-a15b-11e8-8a77-d16b4a117dba.png)

**Comment by camiplata** [comment]
El issue de las referencias fue solucionado, el issue de marco normativo ya se encuentra documentado #236
