### ISSUE TITLE
Estado de amenaza | No se muestra toda la información de la sección

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#235]
El contenido de la sección 'Estado de amenaza' aparece incompleto
Relacionado a Issuee #233 #234

Información que deberia aparecer según mamut:
![image](https://user-images.githubusercontent.com/5700527/43914189-c64c0b08-9bcc-11e8-9ef6-766ebacf0bc2.png)
http://prueba.mamut.biodiversidad.co/edit?id=56718bdcf289f5a40c0cd305#/form/demogra

Información en el catálogo:
![image](https://user-images.githubusercontent.com/5700527/43914217-d5b3090c-9bcc-11e8-8f55-9ebbeb8cb7ab.png)
http://catalogo.biodiversidad.co/file/56718bdcf289f5a40c0cd305/details

@javiesgm tienes un mockup de esta sección para determinar si necesitamos hacer ajustes solo de contenido o también de diseño?

**Comment by javiesgm** [comment]
Sobre el contenido que se despliega en el detalle de la ficha no, tendremos que revisarlo sobre la marcha. 
Pero, sobre la forma como se pinta el estado de amenaza en las tarjetas y en el encabezado de ficha si. Adjunto ambas vistas.

PNG tarjeta: 
![captura de pantalla 2018-08-16 a la s 1 33 54 p m](https://user-images.githubusercontent.com/14220404/44227753-0c943180-a159-11e8-833b-b9e0ac025492.png)

PNG Ficha: 
![captura de pantalla 2018-08-16 a la s 1 34 55 p m](https://user-images.githubusercontent.com/14220404/44227804-32213b00-a159-11e8-9624-abc4f90ff89c.png)

Debe tener tooltip que indique el estado de amenaza.

**Comment by jag2kn** [comment]
La clase aparece implementada como medidas o hechos:

![captura de pantalla de 2018-12-28 11-53-51](https://user-images.githubusercontent.com/321637/50522126-542bb200-0a97-11e9-9465-88f7cee47e17.png)

Sin embargo la estructura de la clase de acuerdo al Plinian Core no corresponde a medidas o hechos:
https://github.com/tdwg/PlinianCore/wiki/ThreatStatusAtomizedClass

![image](https://user-images.githubusercontent.com/5700527/51207560-289f2900-18d9-11e9-908b-522c9b8b02f4.png)

En mamut la implementación también tiene problemas ya que el elemento 'AppliesTo' no esta aplicando de manera independiente para cada autoridad:

![image](https://user-images.githubusercontent.com/5700527/51207647-68661080-18d9-11e9-8fad-e80e1165a24a.png)

**Comment by jag2kn** [comment]
![estado de amenaza_medidas y hechos](https://user-images.githubusercontent.com/321637/51208254-29d15580-18db-11e9-9125-55244d3bb910.png)

**Comment by jag2kn** [comment]
La información de 'AppliesTo'  en categoría Global está siendo guardada erróneamente en el elemento 'country':

![pais](https://user-images.githubusercontent.com/321637/51208312-479eba80-18db-11e9-9e69-afb9e199bc25.png)

**Comment by camiplata** [comment]
Se hicieron los ajustes para mostrar la información de CITES y se hicieron ajustes de visualización pequeños para que los datos se muestren consistentemente.

Fue necesario hacer ajustes particulares en tablesWithoutStructure para agregar los elementos faltantes particulares de esta clase.
