### ISSUE TITLE
DETALLE FICHA | Sinónimos no se están mostrando en la ficha

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#238]
Los sinónimos no aparecen en ninguna parte de la ficha:

Ejemplo de la ficha donde se detectó el problema:
http://catalogo.biodiversidad.co/file/56718bdcf289f5a40c0cd305/details

Las información que aparece en mamut:
![image](https://user-images.githubusercontent.com/5700527/43967603-60cf2ea4-9c8a-11e8-9ab7-1dae1bbdaadb.png)

@javiesgm Cómo se tiene pensado el diseño para está sección?

**Comment by javiesgm** [comment]
No hay diseño sobre esta sección. Comencemos por incorporarla al detalle de ficha y sobre esto comenzamos. Pregunta, ¿esos sinónimos corresponden a otras fichas ?

**Comment by camiplata** [comment]
No, los sinónimos se refieren a nombres alternativos del organismo descrito en la misma ficha.

**Comment by camiplata** [comment]
Se implemento una mejora en el componente de tabla para soportar búsquedas de información dentro de objetos a partir de las ruta de PliC.

La visualización tiene problemas ya que desde mamút se ha documentado incorrectamente el campo fuente con la información de la autoría, es necesario revisar al detalle @camiplata @leobuitrago 

![image](https://user-images.githubusercontent.com/5700527/51213376-e251c600-18e8-11e9-9425-e2e324314250.png)
