### ISSUE TITLE
Nombres comunes | Falta un espacio para poner datos adicionales

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#239]
Actualmente los nombres comúnes se despliegan en el resumen de la fiicha:
![image](https://user-images.githubusercontent.com/5700527/43968659-6f6cf826-9c8d-11e8-96c1-c77ba0580e05.png)

Sin embargo los nombres comunes tienen asociada información adicional de la región y grupo humano, para esta información falta una sección adicional en la vista detallada de la ficha:

Ejemplo de información en mamut:
http://prueba.mamut.biodiversidad.co/edit?id=56718bdcf289f5a40c0cd305#/form/nomeAndClass
http://catalogo.biodiversidad.co/file/56718bdcf289f5a40c0cd305/summary
![image](https://user-images.githubusercontent.com/5700527/43968786-c1c95efc-9c8d-11e8-8c23-aea38fed1ec6.png)

@javiesgm @leobuitrago Donde han considerado incorporar esta información? Directamente ene le resumen junto con los nombre, o en en el detalle?

**Comment by javiesgm** [comment]
En el resumen deben ir algunos, en detalle va la información completa.

**Comment by camiplata** [comment]
Se implemento una mejora en el componente de tabla para soportar búsquedas de información dentro de objetos a partir de las ruta de PliC
