### ISSUE TITLE
Distribución | No se muestra toda la información de la sección

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#243]
El contenido estructurado de la sección 'Distribución' no aparece
Relacionado a Issues #233 #234 #235 #236 #237 #241 #242

Falta que se refleje el sigueinte contenido en la ficha
![image](https://user-images.githubusercontent.com/5700527/43970319-d8b0568e-9c92-11e8-80db-572978398afe.png)

http://prueba.mamut.biodiversidad.co/edit?id=56718bdcf289f5a40c0cd305#/form/habitat
http://catalogo.biodiversidad.co/file/56718bdcf289f5a40c0cd305/details

**Comment by camiplata** [comment]
@javiesgm tennos un mockup sobre como se debería ver esta sección?

**Comment by javiesgm** [comment]
Nop

**Comment by javiesgm** [comment]
Nos toca sobre la marcha, cuando se muestre el contenido completo, revisamos

**Comment by camiplata** [comment]
Esta clase presenta una estructura inconsistente con las demás clases lo que requiere una implementación distinta, hay información por fuera  de las dos estructuras de información base (atomized, Unstructured):

![image](https://user-images.githubusercontent.com/5700527/51195681-96d4f300-18bb-11e9-9880-1002c06c1a78.png)

**Comment by camiplata** [comment]
No se incorpora temporalCoverage en el front-end ya que no hace parte de nuestro perfil de aplicación

**Comment by camiplata** [comment]
Al ser la estructura distinta a otras clases no se puede dar la misma solución de visualización que en las otras clases, por el momento se asegura la visibilidad de los contenidos pero queda pendiente ajustar los estilos de forma más amigable.

![image](https://user-images.githubusercontent.com/5700527/51196233-b6205000-18bc-11e9-934b-60ed4c5a4d82.png)


@camiplata @leobuitrago Reconsiderar la necesidad del 'Scope', histótico actual etc...

**Comment by camiplata** [comment]
Se aplicó el módulo lista de objetos (para contener la información estructurada con texto libre) desarrollado para #234 #237 permitiendo múltiples llamados al módulo para soportar varios 'DistributionScope'

@jag2kn @dapino @javiesgm crear clases css para solucionar los problemas de visualización recurrentes
