### ISSUE TITLE
Usos | No se muestra la información de la sección

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#244]
El contenido estructurado de la sección 'Usos' no aparece
Relacionado a Issues #233 #234 #235 #236 #237 #241 #242 #243 
![image](https://user-images.githubusercontent.com/5700527/43976773-7139987a-9ca7-11e8-8028-8c6f955c8afd.png)

http://prueba.mamut.biodiversidad.co/edit?id=56718bdcf289f5a40c0cd305#/form/uses
http://catalogo.biodiversidad.co/file/56718bdcf289f5a40c0cd305/details

**Comment by camiplata** [comment]
Tener en cuenta los mismo parámetros de estilo que se definan para #270

**Comment by jag2kn** [comment]
56cf97303c16479905cba7f1

**Comment by camiplata** [comment]
Se aplicó el módulo lista de objetos (para contener la información estructurada con texto libre) desarrollado para #234 #237

Fue necesario ajustar el llamado ya que  la clase Uso manejo y conservación tiene un comportamiento distinto a las otras implementadas (anidación inconsistente y excesiva)

![image](https://user-images.githubusercontent.com/5700527/50925492-7ec72480-1420-11e9-9e69-0fed213bdfe0.png)

Por el momento los elementos de 'usos' y 'manejo y conservación' se muestran al mismo nivel en el catálogo, queda pendiente revisar y ajustar la visualización en un nuevo issue.
