### ISSUE TITLE
Invasividad | No se muestra toda la información de la sección

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/biodiversity_catalogue_v2_frontend#254]
No se muestra la información estructurada
Falta que se refleje el siguiente contenido en la ficha:

![image](https://user-images.githubusercontent.com/5700527/48653249-df625400-e9d1-11e8-8be0-f10b6bb331fe.png)

http://catalogo.biodiversidad.co/file/56d04c173c16479905cba817/details
http://prueba.mamut.biodiversidad.co/edit?id=56d04c173c16479905cba817#/form/invasiveness

**Comment by camiplata** [comment]
@javiesgm tennos un mockup sobre como se debería ver esta sección?

**Comment by javiesgm** [comment]
Sobre la marcha también. Cuando esté visible el contenido revisamos.

**Comment by camiplata** [comment]
Se aplicó el módulo lista de objetos (para contener la información estructurada con texto libre) desarrollado para #234 #237

Se corrigió traducción de elemento 'Impacto'; se quitaron los campos nulos; se ajustaron espacios; se ignoraron los identificadores de los objetos con arreglos
